### ISSUE TITLE
Weft: inline style in error pages

### ISSUE THREAD

**Issue by bpeng** [GeoNet/kit#77]
Currently **error responses** are hard coded with[ inline style](https://github.com/GeoNet/kit/blob/master/weft/errors.go#L7), which conflict with our default CSP policy, 

![Screenshot 2020-07-01 10 57 48](https://user-images.githubusercontent.com/1020745/86185140-be8c4980-bb89-11ea-84f5-7243eb1f6c2b.png)

What should we do with these inline styles? we can 

- Remove those styles and return plain error message
- Implement error handler in individual projects
- Allow inline styles

What do you think? 
@sue-h-gns @junghao @CallumNZ

**Comment by CallumNZ** [comment]
I vote plain error message. Couldn't header and bold elements be used to replicate how it currently looks?

**Comment by junghao** [comment]
Plain message, too
